[tool.poetry]
name = "edi-835-parser"
version = "1.0.17"
description = "A simple EDI 835 file format parser."
authors = [""]
license = "MIT"
readme = "README.md"
packages = [{include = "edi_835_parser"}]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^2.0.3"
psycopg2-binary = "^2.9"
python-dotenv = "^1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
